LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := CFLCommImpl
LOCAL_MODULE_FILENAME := CFLCommImpl
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/CFLCommImpl.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../
include $(PREBUILT_SHARED_LIBRARY)
